name: Pelican site CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install pelican-themes
      run: |
        git clone --depth=1 https://github.com/getpelican/pelican-themes.git
    - uses: nelsonjchen/gh-pages-pelican-action@0.1.10
      env:
        GH_PAGES_CNAME: bmdconf.org
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PELICAN_CONFIG_FILE: publishconf.py
