name: Pelican site CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: nelsonjchen/gh-pages-pelican-action@0.1.10
      env:
        PELICAN_CONFIG_FILE: publishconf.py
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
