name: Pelican site CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5
    - uses: nelsonjchen/gh-pages-pelican-action@0.2.0
      env:
        GH_PAGES_CNAME: bmdconf.org
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PELICAN_CONFIG_FILE: publishconf.py
